_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 51
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 8
checkpoint_path:
    value: checkpoints/enet_checkpoint_epoch_best.pth
dataset_path:
    value: /home/kunal6/.cache/kagglehub/datasets/manideep1108/tusimple/versions/5/TUSimple
