_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 51
                - 55
            "2":
                - 1
                - 51
                - 55
            "3":
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 8
epochs:
    value: 25
learning_rate:
    value: 2e-05
model:
    value: ENet
optimizer:
    value: Adam
